# Generated by Django 4.1.3 on 2022-11-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_person_film_works_filmwork_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('Film', 'movie'), ('TV', 'tv_show')], max_length=255),
        ),
    ]
