# Generated by Django 4.1.3 on 2022-11-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_filmwork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('Film', 'movie'), ('Serial', 'q')], max_length=255),
        ),
    ]
